import { alternatePathsField, PageCollectionConfig } from '@jhb.software/payload-pages-plugin'

export const Pages: PageCollectionConfig = {
  slug: 'pages',
  admin: {
    useAsTitle: 'title',
  },
  access: {
    update: () => false,
    create: () => false,
    delete: () => false,
  },
  page: {
    parent: {
      collection: 'pages',
      name: 'parent',
    },
    isRootCollection: true,
  },
  versions: {
    drafts: {
      autosave: true,
    },
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
      localized: true,
    },
    {
      name: 'content',
      type: 'textarea',
      required: true,
      localized: true,
    },
    {
      // normally this group would be generated by the seo plugin
      name: 'meta',
      type: 'group',
      fields: [alternatePathsField()],
    },
  ],
}
